POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "username": "Mr B",
    "password": "12345"
}

###

POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "username": "Mr B",
    "password": "12345"
}

###
POST http://localhost:4000/api/posts
Content-Type: application/json
Authorization: Bearier eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGIzMmI4ZWViMmViOTNlNmMzNWNkMmEiLCJpYXQiOjE2MjI3MDA4MTJ9.ngd26hD00ld8ASg3RQ2nKCIaHkFsAQrJf1I2gr92LDo

{
    "title": "A",
    "description":"Ref",
    "url": "Ref.com",
    "status": "Finished"
}

###
GET http://localhost:4000/api/posts
Authorization: Bearier eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGIzMmI4ZWViMmViOTNlNmMzNWNkMmEiLCJpYXQiOjE2MjI2Mjg0NDB9.E9rF6VGukiNGejz_82-v0AoqXH9hzaxcBsFHZ9FtK6o


### 
PUT http://localhost:4000/api/posts/60b50c783b6ee8784c28c813
Content-Type: application/json
Authorization: Bearier eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGIzMTJhZjJhMzkyMTY0YTQwZWYzNTkiLCJpYXQiOjE2MjIzNjA3NjB9.tSyew-wdFU7ejexA4tiNzVKIclQ9Gy-V2nWwH0-SATs

{
    "title": "ExpressJS",
    "description":"ExpressJS",
    "url": "expressJS.com",
    "status": "Finished"
}


### 
DELETE http://localhost:4000/api/posts/60b371bf56f8ee10d0b71087
Authorization: Bearier eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGIzMTJhZjJhMzkyMTY0YTQwZWYzNTkiLCJpYXQiOjE2MjIzNjA3NjB9.tSyew-wdFU7ejexA4tiNzVKIclQ9Gy-V2nWwH0-SATs
